server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: '/h2/console'
      settings:
        web-admin-password: '123'
  datasource:
    url: 'jdbc:h2:mem:demo_testing'
    username: 'demo_testing'
    password: 'demo_testing'
    driverClassName: 'org.h2.Driver'
  jpa:
    hibernate:
      ddl-auto: create-drop

